//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jogl.Server.ConversationCoordinator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jogl.Server.ConversationCoordinator.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Current_Complete {
            get {
                return ResourceManager.GetString("Current_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Hey {0}! :wave: I’m JOGL, your personal expert assistant.*
        ///I’m here to help you connect with the right people in this community and beyond—based on what you’re working on, what you’re great at and what your current needs are.
        ///Whether you’re looking for collaborators, advice, or just curious about who around you can help—you can ask me things like:
        /// • “Who here has been working with infectious diseases?”
        /// • “Is there anyone who could help me on my project proposal on the implementation of X for Y? Here  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Greeting_New {
            get {
                return ResourceManager.GetString("Greeting_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Welcome back, {0}! :raised_hands: Your JOGL profile is almost set. One last step.*
        ///Now that I’ve got a sense of what you’ve done, I’d love to know what you’re actually working on right now. That way, I can better connect you with people who can help—or who might want to collaborate with you.
        ///You can tell me in your own words, the more details you provide the better understanding I will have and the more relevant your matches will be.  Keep in mind that any information contained in your JOGL profile can b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Onboarding_Complete {
            get {
                return ResourceManager.GetString("Onboarding_Complete", resourceCulture);
            }
        }
    }
}
