//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jogl.Server.PubMed {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jogl.Server.PubMed.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body Regions|A01
        ///Anatomic Landmarks|A01.111
        ///Breast|A01.236
        ///Mammary Glands, Human|A01.236.249,A10.336.532
        ///Nipples|A01.236.500
        ///Extremities|A01.378
        ///Amputation Stumps|A01.378.100
        ///Lower Extremity|A01.378.610
        ///Ankle|A01.378.610.050
        ///Buttocks|A01.378.610.100
        ///Foot|A01.378.610.250
        ///Forefoot, Human|A01.378.610.250.300
        ///Metatarsus|A01.378.610.250.300.480
        ///Toes|A01.378.610.250.300.792
        ///Hallux|A01.378.610.250.300.792.380
        ///Heel|A01.378.610.250.510
        ///Hip|A01.378.610.400
        ///Knee|A01.378.610.450
        ///Leg|A01.378.610.500
        ///T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pubmed_categories {
            get {
                return ResourceManager.GetString("pubmed_categories", resourceCulture);
            }
        }
    }
}
